# Generated by Django 2.1.5 on 2019-01-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190118_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainImage',
            field=models.ImageField(null=True, upload_to='products_upload/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='path',
            field=models.ImageField(upload_to='products_upload/'),
        ),
    ]
