# Generated by Django 2.1.5 on 2019-01-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190118_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_Image',
            new_name='main_image',
        ),
    ]
